---
- name: Create Pi-hole folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole"
    state: directory
    mode: 0755
  become: false

- name: Copy Pi-hole docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/pi-hole-docker-compose.yml.j2
    dest: "{{ config_dir }}/pi-hole/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart pi-hole

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Pi-hole is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
  become: false

# Support deploying custom.list to /etc/pihole so Pihole will
# serve local addresses
- name: Check if local DNS configuration for Pi-Hole exists
  local_action: stat path="/home/jason/code/internet-pi/files/custom.list"
  register: file

- name: Copy local DNS configuration for Pi-Hole
  ansible.builtin.template:
    synchronize: 
     src: files/custom.list
     # dest: "{{ config_dir }}/etc-pihole/{{ item.dest }}"
     dest: "{{ config_dir }}/"/etc/pihole/custom.list"
     mode: 0644
  when: file.stat.exists 

  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
  become: false